### PR TITLE
Update registry to v2.8.0

### PR DESCRIPTION
**Pull request by Page-**
Change-type: minor

### CODE REVIEW

**Comment by dfunckt** [comment]
Isn't it still in beta?

**Comment by Page-** [comment]
https://github.com/distribution/distribution/releases/tag/v2.8.0

**Comment by dfunckt** [comment]
> released this 22 hours ago

I most recently looked last week and was planning to take a look again this week but you're too fast :)

**Comment by Page-** [comment]
@balena-ci I self-certify!

**Comment by Page-** [comment]
@balena-ci republish

**Pull request merged**
