### PR TITLE
Add repo.yml for future open-balena-base updates

### PR DESCRIPTION
**Pull request by Page-**
Change-type: patch

### CODE REVIEW

**Comment by hedss** [comment]
It's expecting a `package.json`, for some reason. Which does raise a question, why is there a `package-lock.json` in the repo...? And we probably want to delete the `versionist.conf.js` as well...

**Comment by dfunckt** [comment]
package-lock.json is an artifact of VB running and we should remove it (and also add it gitignore). versionbot.conf.js is pretty much legacy by now, but up to a point in time that was the only way to get versioning in non-node projects.

**Comment by Page-** [comment]
@balena-ci retest

**Comment by nazrhom** [comment]
@balena-ci retest

**Pull request merged**
