### PR TITLE
Add ability to configure registry as a Hub proxy

### PR DESCRIPTION
**Pull request by dfunckt**
To enable proxying of Docker Hub, set `REGISTRY2_PROXY_ENABLED` to `true`. This will cache public images pulled through this instance. To access private images, also set `REGISTRY2_PROXY_USERNAME` and `REGISTRY2_PROXY_PASSWORD` to appropriate values.

Storage will highly likely be `filesystem`. To configure it specify `REGISTRY2_STORAGEPATH` to a directory into the registry container. Make sure to mount a volume at that path. Also ensure `REGISTRY2_S3_BUCKET` is *unset*, since its presence causes the instance to use S3 for storage.

The only other required env var is `BALENA_REGISTRY2_HOST` which must be set to the host name the instance will listen to.

Change-type: minor

### CODE REVIEW

**Review by toochevere — DISMISSED** [review]

**Comment by dfunckt** [comment]
@balena-ci rebase

**Comment by dfunckt** [comment]
@balena-ci rebase

**Comment by cmfcruz** [comment]
@balena-ci rebase

**Review by cmfcruz — APPROVED** [review]
It works without any known issues. I am approving this.

**Pull request merged**
